global:
  resolve_timeout: 5m

route:
  receiver: oncall-default
  group_by:
    - alertname
    - service
    - topic
    - area
  group_wait: {{ALERTMANAGER_ROUTE_GROUP_WAIT}}
  group_interval: {{ALERTMANAGER_ROUTE_GROUP_INTERVAL}}
  repeat_interval: {{ALERTMANAGER_ROUTE_REPEAT_INTERVAL}}
  routes:
    - receiver: oncall-critical
      matchers:
        - severity = "critical"
      continue: true
      repeat_interval: {{ALERTMANAGER_ROUTE_CRITICAL_REPEAT_INTERVAL}}
    - receiver: oncall-critical-escalation
      matchers:
        - severity = "critical"
      repeat_interval: {{ALERTMANAGER_ROUTE_CRITICAL_ESCALATION_REPEAT_INTERVAL}}
    - receiver: oncall-warning
      matchers:
        - severity = "warning"
      repeat_interval: {{ALERTMANAGER_ROUTE_WARNING_REPEAT_INTERVAL}}

receivers:
  - name: oncall-default
    webhook_configs:
      - url: ${ALERTMANAGER_DEFAULT_WEBHOOK_URL}
        send_resolved: true

  - name: oncall-warning
    webhook_configs:
      - url: ${ALERTMANAGER_WARNING_WEBHOOK_URL}
        send_resolved: true

  - name: oncall-critical
    webhook_configs:
      - url: ${ALERTMANAGER_CRITICAL_WEBHOOK_URL}
        send_resolved: true

  - name: oncall-critical-escalation
    webhook_configs:
      - url: ${ALERTMANAGER_CRITICAL_ESCALATION_WEBHOOK_URL}
        send_resolved: true
