#!/usr/bin/env bash
# shellcheck disable=SC2034

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "This script must be sourced, not executed." >&2
  echo "Use: source tools/local-functional-test-env.sh" >&2
  exit 1
fi

# Base dependencies
export KAFKA_BOOTSTRAP_SERVERS="${KAFKA_BOOTSTRAP_SERVERS:-127.0.0.1:9092}"
export REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
export REDIS_PORT="${REDIS_PORT:-6379}"

# Control-plane local static auth
export CONTROL_AUTH_ENABLED="${CONTROL_AUTH_ENABLED:-true}"
export CONTROL_AUTH_MODE="${CONTROL_AUTH_MODE:-static}"
export CONTROL_AUTH_CREDENTIALS_0_TOKEN="${CONTROL_AUTH_CREDENTIALS_0_TOKEN:-viewer-tenant-a}"
export CONTROL_AUTH_CREDENTIALS_0_READ="${CONTROL_AUTH_CREDENTIALS_0_READ:-true}"
export CONTROL_AUTH_CREDENTIALS_0_WRITE="${CONTROL_AUTH_CREDENTIALS_0_WRITE:-false}"
export CONTROL_AUTH_CREDENTIALS_0_TENANT_PATTERNS_0="${CONTROL_AUTH_CREDENTIALS_0_TENANT_PATTERNS_0:-tenant-a}"
export CONTROL_AUTH_CREDENTIALS_1_TOKEN="${CONTROL_AUTH_CREDENTIALS_1_TOKEN:-writer-tenant-a}"
export CONTROL_AUTH_CREDENTIALS_1_READ="${CONTROL_AUTH_CREDENTIALS_1_READ:-true}"
export CONTROL_AUTH_CREDENTIALS_1_WRITE="${CONTROL_AUTH_CREDENTIALS_1_WRITE:-true}"
export CONTROL_AUTH_CREDENTIALS_1_TENANT_PATTERNS_0="${CONTROL_AUTH_CREDENTIALS_1_TENANT_PATTERNS_0:-tenant-a}"

# Control auth drill defaults
export CONTROL_AUTH_DRILL_BASE_URL="${CONTROL_AUTH_DRILL_BASE_URL:-http://127.0.0.1:8085}"
export CONTROL_AUTH_DRILL_TENANT_ID="${CONTROL_AUTH_DRILL_TENANT_ID:-tenant-a}"
export CONTROL_AUTH_DRILL_CROSS_TENANT_ID="${CONTROL_AUTH_DRILL_CROSS_TENANT_ID:-tenant-b}"
export CONTROL_AUTH_DRILL_ENABLE_CROSS_TENANT_CHECK="${CONTROL_AUTH_DRILL_ENABLE_CROSS_TENANT_CHECK:-1}"
export CONTROL_AUTH_DRILL_READ_TOKEN="${CONTROL_AUTH_DRILL_READ_TOKEN:-${CONTROL_AUTH_CREDENTIALS_0_TOKEN}}"
export CONTROL_AUTH_DRILL_WRITE_TOKEN="${CONTROL_AUTH_DRILL_WRITE_TOKEN:-${CONTROL_AUTH_CREDENTIALS_1_TOKEN}}"

# Local preprod-closure defaults (Alertmanager capture skipped by default)
export PREPROD_TARGET="${PREPROD_TARGET:-local-functional}"
export PREPROD_SKIP_ALERT_CAPTURE="${PREPROD_SKIP_ALERT_CAPTURE:-1}"
export PREPROD_ALERTMANAGER_URL="${PREPROD_ALERTMANAGER_URL:-http://127.0.0.1:9093}"
export PREPROD_AUTH_DRILL_REQUIRED="${PREPROD_AUTH_DRILL_REQUIRED:-1}"
export PREPROD_AUTH_DRILL_COMMAND="${PREPROD_AUTH_DRILL_COMMAND:-tools/control-plane-auth-drill.sh}"
export PREPROD_LOADTEST_COMMAND="${PREPROD_LOADTEST_COMMAND:-tools/loadtest-alert-closure.sh}"
export PREPROD_FAULT_DRILL_COMMAND="${PREPROD_FAULT_DRILL_COMMAND:-tools/fault-drill-closure.sh}"

echo "Loaded local functional test environment defaults."
